server:
  port: 8000
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: myBlog
  username: root
  password: joeytest123...
  charset: utf8
redis:
  addr: 127.0.0.1
  port: 6379
  password:
  DB: 0